serviceMaps:
 serviceName: AdvertisementService
 mappings:
 - version: 1.0
   name: advertisement-service
   description: Create Site Booking
   fromTopic: create-site-booking
   isTransaction: true
   queryMaps:
    - query: INSERT INTO eg_site_booking (uuid, application_no, site_uuid, applicant_name, applicant_father_name, gender, mobile_number, email_id, advertisement_type, from_date, to_date, period_in_days, hoarding_type, structure, is_active, status, tenant_id, additional_detail, created_by, created_date, last_modified_by, last_modified_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);

      basePath: SiteBookings.*
      jsonMaps:

       - jsonPath: $.SiteBookings.*.uuid

       - jsonPath: $.SiteBookings.*.applicationNo

       - jsonPath: $.SiteBookings.*.siteUuid

       - jsonPath: $.SiteBookings.*.applicantName

       - jsonPath: $.SiteBookings.*.applicantFatherName

       - jsonPath: $.SiteBookings.*.gender

       - jsonPath: $.SiteBookings.*.mobileNumber

       - jsonPath: $.SiteBookings.*.emailId

       - jsonPath: $.SiteBookings.*.advertisementType

       - jsonPath: $.SiteBookings.*.fromDate

       - jsonPath: $.SiteBookings.*.toDate

       - jsonPath: $.SiteBookings.*.periodInDays

       - jsonPath: $.SiteBookings.*.hoardingType

       - jsonPath: $.SiteBookings.*.structure

       - jsonPath: $.SiteBookings.*.isActive

       - jsonPath: $.SiteBookings.*.status

       - jsonPath: $.SiteBookings.*.tenantId

       - jsonPath: $.SiteBookings.*.additionalDetail
         type: JSON
         dbType: JSONB

       - jsonPath: $.SiteBookings.*.auditDetails.createdBy

       - jsonPath: $.SiteBookings.*.auditDetails.createdDate

       - jsonPath: $.SiteBookings.*.auditDetails.lastModifiedBy

       - jsonPath: $.SiteBookings.*.auditDetails.lastModifiedDate



 - version: 1.0
   description: Update Site Booking
   fromTopic: update-site-booking
   isTransaction: true
   queryMaps:

    - query: UPDATE eg_site_booking SET application_no = ?, site_uuid = ?, applicant_name = ?, applicant_father_name = ?, gender = ?, mobile_number = ?, email_id = ?, advertisement_type = ?, from_date = ?, to_date = ?, period_in_days = ?, hoarding_type = ?, structure = ?, is_active = ?, status = ?, tenant_id = ?, additional_detail = ?, created_by = ?, created_date = ?, last_modified_by = ?, last_modified_date = ? WHERE uuid = ?;

      basePath: SiteBookings.*
      jsonMaps:

       - jsonPath: $.SiteBookings.*.applicationNo

       - jsonPath: $.SiteBookings.*.siteUuid

       - jsonPath: $.SiteBookings.*.applicantName

       - jsonPath: $.SiteBookings.*.applicantFatherName

       - jsonPath: $.SiteBookings.*.gender

       - jsonPath: $.SiteBookings.*.mobileNumber

       - jsonPath: $.SiteBookings.*.emailId

       - jsonPath: $.SiteBookings.*.advertisementType

       - jsonPath: $.SiteBookings.*.fromDate

       - jsonPath: $.SiteBookings.*.toDate

       - jsonPath: $.SiteBookings.*.periodInDays

       - jsonPath: $.SiteBookings.*.hoardingType

       - jsonPath: $.SiteBookings.*.structure

       - jsonPath: $.SiteBookings.*.isActive

       - jsonPath: $.SiteBookings.*.status

       - jsonPath: $.SiteBookings.*.tenantId

       - jsonPath: $.SiteBookings.*.additionalDetail
         type: JSON
         dbType: JSONB

       - jsonPath: $.SiteBookings.*.auditDetails.createdBy

       - jsonPath: $.SiteBookings.*.auditDetails.createdDate

       - jsonPath: $.SiteBookings.*.auditDetails.lastModifiedBy

       - jsonPath: $.SiteBookings.*.auditDetails.lastModifiedDate
       
       - jsonPath: $.SiteBookings.*.uuid

       

 - version: 1.0
   description: Create Site
   fromTopic: create-site
   isTransaction: true
   queryMaps:

    - query: INSERT INTO eg_site_application (id, uuid, site_id, site_name, site_description, gps_location, site_address, site_cost, site_photograph, structure, size_length, size_width, led_selection, security_amount, powered, others, district_name, ulb_name, ulb_type, ward_number, pincode, additional_detail, created_by, created_date, last_modified_by, last_modified_date, site_type, account_id, status, is_active, tenant_id, booking_start_date, booking_end_date, application_start_date, application_end_date, workflow_status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?::JSONB, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);

      basePath: siteCreationData
      jsonMaps:

       - jsonPath: $.siteCreationData.id

       - jsonPath: $.siteCreationData.uuid

       - jsonPath: $.siteCreationData.siteID

       - jsonPath: $.siteCreationData.siteName

       - jsonPath: $.siteCreationData.siteDescription

       - jsonPath: $.siteCreationData.gpsLocation

       - jsonPath: $.siteCreationData.siteAddress

       - jsonPath: $.siteCreationData.siteCost

       - jsonPath: $.siteCreationData.sitePhotograph

       - jsonPath: $.siteCreationData.structueType

       - jsonPath: $.siteCreationData.sizeLength

       - jsonPath: $.siteCreationData.sizeWidth

       - jsonPath: $.siteCreationData.ledSelection

       - jsonPath: $.siteCreationData.securityAmount

       - jsonPath: $.siteCreationData.powerSelection

       - jsonPath: $.siteCreationData.otherDetails

       - jsonPath: $.siteCreationData.districtName

       - jsonPath: $.siteCreationData.ulbName

       - jsonPath: $.siteCreationData.ulbType

       - jsonPath: $.siteCreationData.wardNumber

       - jsonPath: $.siteCreationData.pinCode

       - jsonPath: $.siteCreationData.additionalDetail
         type: JSON
         dbType: JSONB

       - jsonPath: $.siteCreationData.auditDetails.createdBy

       - jsonPath: $.siteCreationData.auditDetails.createdDate

       - jsonPath: $.siteCreationData.auditDetails.lastModifiedBy

       - jsonPath: $.siteCreationData.auditDetails.lastModifiedDate
       
       - jsonPath: $.siteCreationData.siteType
       
       - jsonPath: $.siteCreationData.accountId
       
       - jsonPath: $.siteCreationData.status
       
       - jsonPath: $.siteCreationData.active
       
       - jsonPath: $.siteCreationData.tenantId
       
       - jsonPath: $.siteCreationData.bookingPeriodStartDate
       
       - jsonPath: $.siteCreationData.bookingPeriodEndDate
       
       - jsonPath: $.siteCreationData.applicationStartDate
       
       - jsonPath: $.siteCreationData.applicationEndDate

       - jsonPath: $.siteCreationData.workFlowStatus
       
       
       
 - version: 1.0
   description: Update Site
   fromTopic: update-site
   isTransaction: true
   queryMaps:

    - query: UPDATE eg_site_application SET site_description = ?, gps_location = ?, site_address = ?, site_cost = ?, site_photograph = ?, structure = ?, size_length = ?, size_width = ?, led_selection = ?, security_amount = ?, powered = ?, others = ?, district_name = ?, ulb_name = ?, ulb_type = ?, ward_number = ?, pincode = ?, additional_detail = ?::JSONB, last_modified_by = ?, last_modified_date = ?, site_type = ?, status = ?, is_active = ?, booking_start_date = ?, booking_end_date = ?, application_start_date = ?, application_end_date = ?, workflow_status = ? WHERE uuid = ? AND id = ?;

      basePath: siteUpdationData
      jsonMaps:

       - jsonPath: $.siteUpdationData.siteDescription

       - jsonPath: $.siteUpdationData.gpsLocation

       - jsonPath: $.siteUpdationData.siteAddress

       - jsonPath: $.siteUpdationData.siteCost

       - jsonPath: $.siteUpdationData.sitePhotograph

       - jsonPath: $.siteUpdationData.structueType

       - jsonPath: $.siteUpdationData.sizeLength

       - jsonPath: $.siteUpdationData.sizeWidth

       - jsonPath: $.siteUpdationData.ledSelection

       - jsonPath: $.siteUpdationData.securityAmount

       - jsonPath: $.siteUpdationData.powerSelection

       - jsonPath: $.siteUpdationData.otherDetails

       - jsonPath: $.siteUpdationData.districtName

       - jsonPath: $.siteUpdationData.ulbName

       - jsonPath: $.siteUpdationData.ulbType

       - jsonPath: $.siteUpdationData.wardNumber

       - jsonPath: $.siteUpdationData.pinCode

       - jsonPath: $.siteUpdationData.additionalDetail
         type: JSON
         dbType: JSONB

       - jsonPath: $.siteUpdationData.auditDetails.lastModifiedBy

       - jsonPath: $.siteUpdationData.auditDetails.lastModifiedDate
       
       - jsonPath: $.siteUpdationData.siteType
       
       - jsonPath: $.siteUpdationData.status
       
       - jsonPath: $.siteUpdationData.active
       
       - jsonPath: $.siteUpdationData.bookingPeriodStartDate
       
       - jsonPath: $.siteUpdationData.bookingPeriodEndDate
       
       - jsonPath: $.siteUpdationData.applicationStartDate
       
       - jsonPath: $.siteUpdationData.applicationEndDate

       - jsonPath: $.siteUpdationData.workFlowStatus
       
       - jsonPath: $.siteUpdationData.uuid

       - jsonPath: $.siteUpdationData.id

       